version: "3"

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./spring-boot-server      
    environment:
      - DBPASSWD=tutopwd
      - DBUSERNAME=tutorialsuser
      - DBNAME=tutorialsdb
      - DBHOST=db
    ports:
      - "8082:8080"
    depends_on:
      - db
  frontend:
    build: 
      context: ./angular-14-client
    environment:
      - BACKEND=localhost:8082
    ports:
      - "8081:80"
    depends_on:
      - backend