apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wissemgh5/pfe_backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:  # Add environment variables here
            - name: DBPASSWD
              value: tutopwd
            - name: DBUSERNAME
              value: tutorialsuser
            - name: DBNAME
              value: tutorialsdb
            - name: DBHOST
              value: db
