apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner
spec:
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    securityGroupSelector:
      Name: "clusteralpha-node"
    subnetSelector:
      karpenter.sh/discovery: clusteralpha
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - t3.small
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 172800