apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: sonarport
  selector:
    name: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        name: sonarqube
    spec:
      containers:
        - image: sonarqube:alpine
          name: sonarqube
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              value: password
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://db:5432/sonar"
            - name: SONARQUBE_JDBC_USERNAME
              value: "sonar"
          ports:
            - containerPort: 9000
              name: sonarqube
          resources:
            requests:
              memory: "1Gi"  # Request 1 GiB of RAM
            limits:
              memory: "1.5Gi"