name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend image
        run:  |
          cd ./spring-boot-server
          # Create a timestamp variable
          timestamp=$(date +%Y%m%d%H%M%S)
          # Build the Docker image with a timestamp tag
          docker build -t pfe_backend:${timestamp} .
      - name: Build frontend image
        run: |
          cd ./angular-14-client
          # Create a timestamp variable
          timestamp=$(date +%Y%m%d%H%M%S)
          # Build the Docker image with a timestamp tag
          docker build -t pfe_frontend:${timestamp} .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Backend Image to Docker Hub
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          docker tag pfe_backend:${timestamp} ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:${timestamp}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:${timestamp}

      - name: Push Frontend Image to Docker Hub
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          docker tag pfe_frontend:${timestamp} ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:${timestamp}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:${timestamp}
