name: Docker Image CI

on:
  push:
    branches: [ "githubActions" ]
  pull_request:
    branches: [ "githubActions" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker-compose
        run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests

  build_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Compose
        run: docker-compose build

  push_backend:
    runs-on: ubuntu-latest
    needs: [build_docker_compose]
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Backend Image to Docker Hub
        run: |
          docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backendwiss:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backendwiss:latest

  push_frontend:
    runs-on: ubuntu-latest
    needs: [build_docker_compose]
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontendwiss:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontendwiss:latest
