name: Docker Image CI

on:
  push:
    branches: [ "githubActions" ]
  pull_request:
    branches: [ "githubActions" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker-compose
        run: |
          mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
          # Package the artifact (e.g., JAR file) as an artifact
          cp ./spring-boot-server/target/*.jar $GITHUB_WORKSPACE/my-app.jar
        # Publish the artifact for use in subsequent jobs
        continue-on-error: true
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        # Create a temporary workspace for this job
        working-directory: ${{ github.workspace }}/build_maven

  build_docker_compose:
    runs-on: ubuntu-latest
    needs: [build_maven]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Compose
        run: |
          # Retrieve the artifact from the previous job
          cp $GITHUB_WORKSPACE/my-app.jar ./spring-boot-server/target/my-app.jar
          docker-compose build
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        # Use the same temporary workspace as build_maven
        working-directory: ${{ github.workspace }}/build_maven

  push_backend:
    runs-on: ubuntu-latest
    needs: [build_docker_compose]
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Backend Image to Docker Hub
        run: |
          docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  push_frontend:
    runs-on: ubuntu-latest
    needs: [build_docker_compose]
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
