name: Docker Image CI

on:
  push:
    branches: [ "githubActions" ]
  pull_request:
    branches: [ "githubActions" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the spring app
        run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
          # Package the artifact (e.g., JAR file)
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: spring-boot-server/target/*
          format: zip

  build_docker_compose:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    needs: [build_maven]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.zip
      - name: Unzip Artifact
        run: unzip spring-boot-server/target/app.zip -d spring-boot-server/target/
      - name: Unzip Artifact
        run: ls spring-boot-server/target/
      - name: Build backend image
        run:  |
          cd ./spring-boot-server
          docker build .  -t pfe_backend
      - name: Build frontend image
        run: |
          cd ./angular-14-client  
          docker build . -t pfe_frontend
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Backend Image to Docker Hub
        run: |
          docker tag pfe_backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest
      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag pfe_frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
