name: Docker Image CI

on:
  push:
    branches: [ "githubActions" ]
  pull_request:
    branches: [ "githubActions" ]

jobs:
  build:

    runs-on: docker pull maven:3.3.9-jdk-8-onbuild
    steps:
    - uses: actions/checkout@v3
    - name: building spring artifact
    - run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
  builddocker:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker-compose
    - run: docker-compose build  
