name: Docker Image CI

on:
  push:
    branches: [ "BaseImages" ]
  pull_request:
    branches: [ "BaseImages" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the spring app
        run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
          # Package the artifact (e.g., JAR file)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar
  build_docker_images:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    needs: [build_maven]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: spring-boot-server/target

      - name: Unzip Artifact
        run: ls spring-boot-server/target/
      - uses: mr-smithers-excellent/docker-build-push@v6
        id: build-image-backend
        name: build-image-backend
        with:
          image: wissemgh5/pfe_backend
          registry: docker.io
          dockerfile: ./spring-boot-server/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          push: true
          tags: ${{ github.sha }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        id: build-image-frontend
        name: build-image-frontend
        with:
          image: wissemgh5/pfe_frontend
          registry: docker.io
          dockerfile: ./angular-14-client/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          push: true
          tags: ${{ github.sha }}
          
  # update-manifest-stage:
  #  runs-on: ubuntu-latest
  #  needs: ['build_docker_images']
  #  environment: GITHUB
  #  steps:
  #     - uses: actions/checkout@v3
  #       with:
  #           repository: wissem1996/PFE
  #           ref: 'master'
  #           token: ${{ secrets.G_TOKEN }}
  #     - name: setup git config
  #       run: |
  #           git config --global user.email ${{secrets.EMAIL }}
  #           git config --global user.name ${{ secrets.ACTOR }}
  #           echo ${{ github.sha }}
  #           sed -i "s#wissemgh5.*#wissemgh5/pfe_backend:${{ github.sha }}#g" k8s/backend/backend-deployment.yaml
  #           sed -i "s#wissemgh5.*#wissemgh5/pfe_frontend:${{ github.sha }}#g" k8s/frontend/frontend-deployment.yaml
  #           git add -A
  #           git commit -am "Update image for - ${{ github.sha }}"
  #     - run: echo ${{ github }}
  #     - run: git push origin master     
