name: Docker Image CI

on:
  push:
    branches: [ "securityTests" ]
  pull_request:
    branches: [ "securityTests" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the spring app
        run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
          # Package the artifact (e.g., JAR file)
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar

  build_docker_compose:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    needs: [build_maven]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar

      - name: Build Docker Compose & push images
        run: docker-compose build
      - name: show images
        run: docker images
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pfe_backend:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Push Backend Image to Docker Hub
        run: |
          docker tag pfe_backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest
      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag pfe_frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
