name: Docker Image CI

on:
  push:
    branches: [ "githubActions" ]
  pull_request:
    branches: [ "githubActions" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker-compose
        run: mvn clean install -f ./spring-boot-server/pom.xml -DskipTests
          # Package the artifact (e.g., JAR file)
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar

  build_docker_compose:
    runs-on: ubuntu-latest
    needs: [build_maven]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./spring-boot-server/target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar

      - name: Build Docker Compose
        run: docker-compose build
      - name: show images
        run: docker images
          
  push_backend:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    needs: [build_docker_compose]
    steps:
        - name: Login to Docker Hub
          
          run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          env:
            DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        - name: Push Backend Image to Docker Hub
          run: |
            docker tag pfe_backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_backend:latest

  push_frontend:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    needs: [build_docker_compose]
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push Frontend Image to Docker Hub
          run: |
            docker tag pfe_frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/pfe_frontend:latest
